# Create a wrapper chart to reference Grafana upstream
# Purpose is to override configs while keeping upstream chart intact
# Keep things clean without downloading the whole chart to local repo...
apiVersion: v2
name: grafana
version: 1.0.0
description: Grafana deployment for monitoring and visualisation
dependencies:
  - name: grafana
    version: 10.0.0
    repository: https://grafana.github.io/helm-charts/
