global:
  # hostname will default to this domain
  domain: argocd.local.io

server: 
  ingress: 
    enabled: true
  

  params:
    # For simplicity, redirect to port 80 first
    server.insecure: true

