# Create a wrapper chart to reference Prometheus upstream
# Purpose is to override configs while keeping upstream chart intact
# Keep things clean without downloading the whole chart to local repo...
apiVersion: v2
name: prometheus
version: 1.0.0
description: Prometheus deployment for monitoring
dependencies:
  - name: prometheus
    version: 27.39.0
    repository: https://prometheus-community.github.io/helm-charts